version: 2.1

jobs:
  build:
    docker:
      - image: ruby:latest

    working_directory: https://github.com/AinaR07/cc-d4-rice-cooker-ci-AinaR07/tree/feature/ruby

    steps:
      - checkout

      - run:
          name: Install Bundler
          command: gem install bundler

      - run:
          name: Install dependencies
          command: bundle install

      - run:
          name: Run RuboCop
          command: rubocop RiceCooker.rb

      - run:
          name: Run tests
          command: bundle exec ruby rice_cooker_test.rb

workflows:
  version: 2
  build:
    jobs:
      - build
